### ISSUE TITLE
실행이 되지 않음

### ISSUE THREAD

**Issue by gipiman** [seunggabi/excel-merge-tool#14]
1. git clone
2. npm install
3. npm start
4. xlsx 모듈을 찾을 수 없음
5. npm install xlsx
6. npm start
7. files 디렉토리를 찾을 수 없음
-> ??

**Comment by seunggabi** [comment]
@gipiman 
files디렉토리와
files/output
디렉토리를 만드시면 에러가 안날것같습니다.
해당기능 수정하겟습니다.

확인감사합니다.
하나덧붙이면 files밑으로 머지하고 싶은 엑셀을 모아두시면 아웃풋에 만들어집니다

**Comment by seunggabi** [comment]
/files
/files/output
디렉터리 추가 완료 :)
