### ISSUE TITLE
전체 셀 업데이트 하도록!?

### ISSUE THREAD

**Issue by seunggabi** [seunggabi/excel-merge-tool#20]
+ 셀 수식 계산
+ 줄바꿈

두가지가 일어나도록 !?
cell 마다 r, v, w, s, t, 데이터를 확인해야함...

**Comment by seunggabi** [comment]
차선책
읽고 머지
머지 후 저장
다시 읽고 다시쓰기

**Comment by seunggabi** [comment]
읽고 다시쓰기 실패

**Comment by gipiman** [comment]
해결한 write options
`{ bookType: 'xlsx', cellDates: true, bookSST: true, compression: true, type: 'binary' }`
해결한줄 알았는데 결과값만 복사해 온것이 었음...

**Comment by seunggabi** [comment]
줄바꿈 스타일 wrapText: true로 해결
수식 해야함.

**Comment by seunggabi** [comment]
수식은 사용자에게 맞기는 쪽으로..?
